### ISSUE TITLE
multi instance support

### ISSUE THREAD

**Issue by doing-fine-thanks** [alisomay/libpd-rs#20]
Hey! I was curious if there were any plans/timelines for multi instance support. I am working some [Godot](https://godotengine.org) addons using this library (via [gdext](https://github.com/godot-rust/gdext)), but I am sort of stuck until multiple instances are supported. The global allocation means all patches play from all audio sources in a game scene at the same time (unless I am missing something).

Thank you so much in advanced/for all y'alls work!

**Comment by alisomay** [comment]
There were no plans currently but since a need has appeared, actually why not. 
It is just that probably I'll not dive in and implement it until a few months later on the other hand I'm always open to PRs. 

I kind of burnt myself out with these projects 
- https://github.com/alisomay/rytm-rs
- https://github.com/alisomay/rytm-external
 and need a break 😅.
 
 On the other hand it is really nice to hear that somebody is using this ✨ 
 
 About your issue, I understood the global instance as
 - There is only one instance of pd is allocated which means one audio processing block.
 - I didn't check how the multi instance feature behaves yet.
 
 I am not familiar with game audio systems but I assume that you have some audio sources and they generate or process audio (each one has their own processing block) and then all is mixed in the main high prio audio thread?

**Comment by doing-fine-thanks** [comment]
Hey! Super understand the burn out (hence me getting into game development after ~6 years doing big-data architecture work). 

In terms of game audio: what you outlined is my understanding of it too (admittedly very new to game engines and rust programming). 

My current usage of this library is passing a buffer stored on each audio object in a game scene to the global pd object, taking the buffer and handing them off a [`Generator` playback](https://docs.godotengine.org/en/stable/classes/class_audiostreamgeneratorplayback.html) in `Godot` and letting the audio server code manage the mix/spatialization of the various elements. 

The issues I am running into are:
 - Loading of multiple patches (each audio source in the game may  need a different patch, and these audio sources would have to be processes ~60 times a second).
 - Stuttering when trying to play more than a single audio source as the global instance swaps between more than a single patch. 
 
 I can take a look, but as a Rust nooby, I am not totally sure where to begin with that.

**Comment by alisomay** [comment]
I see, it seems that multi instance support seems a nice fit to widen your bottle neck. 
It shouldn't be very complicated to add that. I was planning to do it sometime anyway. 
I'll see what I can do and let you know here if there are any updates ✨ 
If there are other contributor candidates reading this issue, I'm open to PRs.

**Comment by doing-fine-thanks** [comment]
Thank you so much!

**Comment by alisomay** [comment]
I took a look at it this morning. 
I think it might take approximately ~3 days of work to
- Reorganize the existing data structures to support multi instance while keeping the single instance functionality and put those under feature flags. 
- Update the comments, tests and doc tests to support multi instance
- Change convenience module to support both cases single instance and multi instance
- Add multi instance examples and introduction to the tutorial
- Test for all major platforms
- Fix bugs and obscure memory errors along the way. 

I'll try to look at these whenever I have enough time budget to allocate. 
I'll give updates.

**Comment by alisomay** [comment]
It is progressing with no blocks. 
I can not work on it very frequently but probably finish it some time this month.

**Comment by alisomay** [comment]
Waiting for these two
- https://github.com/libpd/libpd/pull/383
- https://github.com/pure-data/pure-data/pull/2165

**Comment by danomatika** [comment]
@doing-fine-thanks "Multi-instance" refers to entirely separate pure data environments. Think VST environments where audio plugins are running at different places and along different signal chains. It seems like what you are having issues with is working with multiple abstractions, aka instances of the same patch, within a single Pure Data environment. In this case, you can use the unique $0 id to differentiate between them and/or your own messaging structures. If you can make it work within a single desktop Pd, you don't need multiple Pd instances.

**Comment by alisomay** [comment]
It is super late 🙂 
But both fixes are merged upstream and I could only find the time now.
Only some documentation changes and minor refactors left with this.
- https://github.com/alisomay/libpd-rs/pull/22

It will merge soon so we can close this.

**Comment by alisomay** [comment]
Pr is merged, I'll close this when the crate is published.

**Comment by alisomay** [comment]
Published
- https://crates.io/crates/libpd-rs/0.2.0

Closing 👍
